apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-shift
  labels:
    app: remote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remote
  template:
    metadata:
      labels:
        app: remote
    spec:
      containers:
        - name: remote-shift
          image: hublo/mf-nginx_remote-shift
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: remote-shift
  labels:
    app: remote
spec:
  selector:
    app: remote
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
